### ISSUE TITLE
binding this to an MVC view for a dynamic ASP MVC core view

### ISSUE THREAD

**Issue by fasteddys** [pdevito3/QueryKit#1]
Hello how can we bind the query to take dynamic query, **based on user selection** 

Below is an example, can you help with a sample on how this accept user selected options on an album or dynamic/expando object 

I can share a link also...

![image](https://user-images.githubusercontent.com/96149622/236101044-89897166-5723-4753-aa44-d85a80521a23.png)

**Comment by pdevito3** [comment]
I'm not too familiar with MVC, but I'd expect that you could bind each of those controls to an object that gets passed in wherever your queryable is for the page and they can be transformed appropriately (or maybe you even build in transformation methods to the controls)

Regardless, all QueryKit is doing is taking in a string with the QueryKit syntax and parsing it to an expression that can be used on a queryable. If you can create that filter string from binded values from your controls, that's all you'd need.
