### ISSUE TITLE
Add "Not In" Comparison operator

### ISSUE THREAD

**Issue by AlexMKotcz** [pdevito3/QueryKit#17]
Currently, we have the "In" comparison operator:

![image](https://github.com/pdevito3/QueryKit/assets/17142585/0cdb5982-c2d7-406d-8da4-188828302858)

Could we get the "Not In" operator as well?

Use case:
Do a database filter where items IDs are not in a list of items.
Example: `"""Id !^^ [23, 21, 20]"""`

**Comment by pdevito3** [comment]
Yeah, this slipped through the cracks. Good call. New release just pushed that includes it.
