### ISSUE TITLE
ParsingException does not inherit from QueryKitException

### ISSUE THREAD

**Issue by jthomperoo** [pdevito3/QueryKit#57]
Hi,

Thanks again for this project, it's become really useful for me and has made my APIs much easier to use!

When I added the changes for #25 to introduce a base exception that would allow an easy way to catch any exception QueryKit can throw I forgot to update `ParsingException` to extend the new `QueryKitException`.

This means that if a `ParsingException` is thrown it is not caught by a catch for `QueryKitException`.

I've made the changes in a pull request to fix this.

Thanks!

**Comment by pdevito3** [comment]
Awesome, thanks for the PR! Glad to hear you're liking it 🙂

Will try and get a patch up later today. 

Maybe one day I'll add some CD to automate it 😂
